import React, { useState } from 'react'
import { Share2, Download, Copy, Eye, Calendar, MapPin, Clock, FileText, Loader2, Sparkles } from 'lucide-react'
import apiService from '../services/api'

const ShareableCards = ({ incidents, user }) => {
  const [selectedIncident, setSelectedIncident] = useState(null)
  const [generatingCard, setGeneratingCard] = useState(false)

  const generateCard = async (incident) => {
    setGeneratingCard(true)
    
    try {
      // Generate AI summary if user has premium
      let aiSummary = incident.userNotes || 'Police encounter recorded'
      if (user.subscriptionStatus === 'premium') {
        try {
          aiSummary = await apiService.generateIncidentSummary(incident)
        } catch (error) {
          console.error('Error generating AI summary:', error)
          // Fall back to user notes or default
        }
      }

      const cardData = {
        id: Date.now(),
        incidentId: incident.recordId,
        title: 'Police Encounter Documentation',
        summary: aiSummary,
        location: incident.location ? 
          `${incident.location.latitude.toFixed(4)}, ${incident.location.longitude.toFixed(4)}` : 
          'Location not recorded',
        timestamp: new Date(incident.timestamp).toLocaleString(),
        duration: incident.duration ? `${Math.floor(incident.duration / 60)}:${(incident.duration % 60).toString().padStart(2, '0')}` : 'N/A',
        state: user.currentState,
        recordingType: incident.recordingType || 'none',
        hasRecording: !!incident.recordedData,
        alertSent: incident.alertSent || false,
        ipfsUrl: incident.ipfsUrl || null,
        aiGenerated: user.subscriptionStatus === 'premium'
      }
      
      return cardData
    } catch (error) {
      console.error('Error generating card:', error)
      return null
    } finally {
      setGeneratingCard(false)
    }
  }

  const shareCard = async (incident) => {
    const card = await generateCard(incident)
    
    const shareText = `🚨 Police Encounter Documentation
📅 ${card.timestamp}
📍 ${card.location}
⏱️ Duration: ${card.duration}
📝 ${card.summary}

Generated by KnowMyRights.ai`

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Police Encounter Documentation',
          text: shareText,
          url: window.location.href
        })
      } catch (err) {
        console.log('Share cancelled')
      }
    } else {
      // Fallback to clipboard
      await navigator.clipboard.writeText(shareText)
      alert('Card content copied to clipboard!')
    }
  }

  const downloadCard = async (incident) => {
    const card = await generateCard(incident)
    
    const cardHtml = `
<!DOCTYPE html>
<html>
<head>
    <title>Police Encounter Documentation</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
        .card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; background: white; }
        .header { text-align: center; margin-bottom: 20px; }
        .field { margin-bottom: 10px; }
        .label { font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; color: #666; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="card">
        <div class="header">
            <h1>Police Encounter Documentation</h1>
            <p>Generated by KnowMyRights.ai</p>
        </div>
        <div class="field"><span class="label">Date & Time:</span> ${card.timestamp}</div>
        <div class="field"><span class="label">Location:</span> ${card.location}</div>
        <div class="field"><span class="label">State:</span> ${card.state}</div>
        <div class="field"><span class="label">Duration:</span> ${card.duration}</div>
        <div class="field"><span class="label">Recording Type:</span> ${card.recordingType}</div>
        <div class="field"><span class="label">Has Recording:</span> ${card.hasRecording ? 'Yes' : 'No'}</div>
        <div class="field"><span class="label">Alert Sent:</span> ${card.alertSent ? 'Yes' : 'No'}</div>
        <div class="field"><span class="label">Notes:</span> ${card.summary}</div>
        <div class="footer">
            <p>This document was automatically generated for legal documentation purposes.</p>
        </div>
    </div>
</body>
</html>`

    const blob = new Blob([cardHtml], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `incident-card-${Date.now()}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (incidents.length === 0) {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-textPrimary mb-4">
            Shareable Documentation Cards
          </h1>
          <p className="text-lg text-textSecondary max-w-3xl mx-auto">
            Auto-generated shareable cards for your recorded incidents. Perfect for sharing with legal counsel or support networks.
          </p>
        </div>

        <div className="card text-center py-12">
          <FileText className="h-16 w-16 text-textSecondary mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-textPrimary mb-2">
            No Incidents Recorded Yet
          </h3>
          <p className="text-textSecondary mb-6">
            Record your first police encounter to generate shareable documentation cards.
          </p>
          <button className="btn-primary">
            Record First Incident
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold text-textPrimary mb-4">
          Your Documentation Cards
        </h1>
        <p className="text-lg text-textSecondary max-w-3xl mx-auto">
          Shareable cards for your recorded incidents. Perfect for legal documentation and sharing with support networks.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {incidents.map((incident) => (
          <div key={incident.recordId} className="card hover:shadow-modal transition-all">
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1">
                <h3 className="font-semibold text-textPrimary mb-2">
                  Police Encounter
                </h3>
                <div className="space-y-1 text-sm text-textSecondary">
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4" />
                    {new Date(incident.timestamp).toLocaleDateString()}
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4" />
                    {new Date(incident.timestamp).toLocaleTimeString()}
                  </div>
                  {incident.location && (
                    <div className="flex items-center gap-2">
                      <MapPin className="h-4 w-4" />
                      {incident.location.latitude.toFixed(4)}, {incident.location.longitude.toFixed(4)}
                    </div>
                  )}
                </div>
              </div>
              <div className="flex flex-col gap-1">
                {incident.recordedData && (
                  <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded">
                    Recorded
                  </span>
                )}
                {incident.alertSent && (
                  <span className="text-xs bg-red-100 text-red-800 px-2 py-1 rounded">
                    Alert Sent
                  </span>
                )}
              </div>
            </div>

            {incident.userNotes && (
              <div className="mb-4">
                <p className="text-sm text-textPrimary bg-gray-50 p-3 rounded-md">
                  {incident.userNotes.length > 100 
                    ? incident.userNotes.substring(0, 100) + '...'
                    : incident.userNotes
                  }
                </p>
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={() => setSelectedIncident(incident)}
                className="flex-1 btn-secondary flex items-center justify-center gap-2 text-sm py-2"
              >
                <Eye className="h-4 w-4" />
                View
              </button>
              <button
                onClick={() => shareCard(incident)}
                disabled={generatingCard}
                className="flex-1 btn-primary flex items-center justify-center gap-2 text-sm py-2"
              >
                <Share2 className="h-4 w-4" />
                Share
              </button>
              <button
                onClick={() => downloadCard(incident)}
                disabled={generatingCard}
                className="btn-secondary flex items-center justify-center p-2"
              >
                <Download className="h-4 w-4" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Loading State */}
      {generatingCard && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-surface rounded-lg p-6 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
            <p className="text-textPrimary">Generating shareable card...</p>
          </div>
        </div>
      )}

      {/* Incident Detail Modal */}
      {selectedIncident && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-textPrimary">
                  Incident Details
                </h2>
                <button
                  onClick={() => setSelectedIncident(null)}
                  className="text-textSecondary hover:text-textPrimary"
                >
                  ✕
                </button>
              </div>

              <div className="space-y-6">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-textSecondary mb-1">
                      Date & Time
                    </label>
                    <p className="text-textPrimary">
                      {new Date(selectedIncident.timestamp).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-textSecondary mb-1">
                      Duration
                    </label>
                    <p className="text-textPrimary">
                      {selectedIncident.duration 
                        ? `${Math.floor(selectedIncident.duration / 60)}:${(selectedIncident.duration % 60).toString().padStart(2, '0')}`
                        : 'N/A'
                      }
                    </p>
                  </div>
                </div>

                {selectedIncident.location && (
                  <div>
                    <label className="block text-sm font-medium text-textSecondary mb-1">
                      Location
                    </label>
                    <p className="text-textPrimary">
                      {selectedIncident.location.latitude}, {selectedIncident.location.longitude}
                    </p>
                  </div>
                )}

                {selectedIncident.userNotes && (
                  <div>
                    <label className="block text-sm font-medium text-textSecondary mb-1">
                      Notes
                    </label>
                    <div className="bg-gray-50 rounded-md p-4">
                      <p className="text-textPrimary whitespace-pre-wrap">
                        {selectedIncident.userNotes}
                      </p>
                    </div>
                  </div>
                )}

                <div className="flex gap-4">
                  <button
                    onClick={() => shareCard(selectedIncident)}
                    className="btn-primary flex items-center gap-2"
                  >
                    <Share2 className="h-4 w-4" />
                    Share Card
                  </button>
                  <button
                    onClick={() => downloadCard(selectedIncident)}
                    className="btn-secondary flex items-center gap-2"
                  >
                    <Download className="h-4 w-4" />
                    Download
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default ShareableCards
